version: '3.8'
services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_manager_api
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: 